# Generated by Django 2.2.5 on 2019-09-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Word',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('times', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Common_Word',
            fields=[
                ('word', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('times', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=5000)),
                ('output_text', models.CharField(max_length=5000)),
                ('total_words', models.IntegerField(default=0)),
                ('common_words', models.IntegerField(default=0)),
                ('uncommon_words', models.IntegerField(default=0)),
                ('business_words', models.IntegerField(default=0)),
                ('analysis_date', models.DateTimeField(verbose_name='analysis date')),
            ],
        ),
    ]
