# Generated by Django 2.2.5 on 2019-09-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_word',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
