# Generated by Django 3.0 on 2020-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexi', '0005_auto_20200113_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='suggestions',
            field=models.ManyToManyField(related_name='_word_suggestions_+', to='lexi.Word'),
        ),
    ]
